export const UPDATES: { text: string; date: string }[] = [
  { text: 'Curățenie → Rapoarte → Casă staff: la „+ Sumă încasată" / „− Sumă cheltuită" poți alege acum și o dată din trecut (implicit rămâne azi) — util când adaugi cu întârziere o încasare/cheltuială mai veche, fără s-o înregistrezi greșit pe ziua curentă', date: '2026-09-02' },
  { text: 'Generator Marketing → Imagini: mod nou „📋 Script din referință" — încarci o poză cu stilul dorit (a ta sau găsită oriunde) și AI-ul o analizează, scriindu-ți un ghid tehnic de fotografiere (unghi, lumină, culoare/filtru, recuzită) pe care îl folosești ca să faci tu poza, cu telefonul/camera, în afara aplicației. Se salvează în același istoric ca editările de poze', date: '2026-08-28' },
  { text: 'Generator Marketing extins — istoric per apartament (fiecare generare de texte se salvează, poți reveni la orice variantă veche) + tab nou „Imagini": încarci o poză reală, scrii ce vrei modificat (lumină, dezordine, text pe imagine, crop) și AI-ul editează poza, cu istoric de editări și descărcare. Necesită 2 tabele noi în Supabase (marketing_texte, marketing_imagini) — vezi mesaj separat', date: '2026-08-28' },
  { text: 'Nou: Generator Marketing — pentru orice apartament, AI-ul (specializat pe cazare turistică/regim hotelier, nu vânzări/închirieri clasice) scrie 8 materiale diferite (Facebook, Instagram, Instagram Story, Reel script, TikTok script, Newsletter, Email marketing, Google Business) din specificațiile apartamentului + notițe opționale + poze opționale (nu se salvează, doar pentru generare)', date: '2026-08-28' },
  { text: 'Fix major: sincronizarea automată cu 5starDesk (orară + cron de noapte) nu prelua deloc numărul real de oaspeți, deși API-ul îl trimite (adulți + copii) — nr_persoane rămânea mereu gol, iar lenjeriile se estimau tot din capacitatea maximă a apartamentului, nu din oaspeții reali; acum se salvează corect la fiecare sincronizare, iar valorile deja calculate greșit pentru curățeniile neîncepute au fost corectate', date: '2026-08-20' },
  { text: 'Stoc lenjerii (Staff + Curățenie): pe lângă „+ Adaugă", acum ai și „− Scade" pentru corectare manuală a stocului', date: '2026-08-17' },
  { text: 'Fix major: numărul de lenjerii din Staff arăta mereu „1" indiferent de apartament — Airbnb/Booking nu trimit numărul real de oaspeți prin sincronizare, iar acel câmp gol nu era tratat; acum se estimează din capacitatea maximă a apartamentului (2 oaspeți → 1 lenjerie, 4 → 2, 6 → 3, ca înainte), atât la afișare cât și la scăderea reală din stoc', date: '2026-08-12' },
  { text: 'Task-uri: tab nou „🔁 Recurente" (apare doar când ai task-uri recurente configurate) — arată ce trebuie finalizat acum, cu avans înainte de scadență, plus lista completă de task-uri recurente cu editare/ștergere; până acum șabloanele recurente erau complet invizibile după creare', date: '2026-08-12' },
  { text: 'Cheltuieli și Facturi: pe lângă tragere (⠿), acum ai și săgeți ↑↓ lângă fiecare apartament pentru mutare rapidă, cu un singur click — mai simplu decât să tragi toată secțiunea', date: '2026-08-12' },
  { text: 'Cheltuieli și Facturi: se pot reordona acum direct din aceste pagini (⠿), nu doar din Apartamente — toate trei rămân sincronizate pe aceeași ordine', date: '2026-08-12' },
  { text: 'Fix major: mesajele „Confirmare Check-in" și „Date acces" editate din Setări nu erau folosite niciodată la trimitere — Dashboard-ul afișa mereu textul generic din cod, indiferent ce salvai; acum se trimite exact textul salvat', date: '2026-08-12' },
  { text: 'Apartamente: reordonare prin tragere (⠿ în colțul cardului) — ordinea aleasă se păstrează și în Facturi + Cheltuieli', date: '2026-08-12' },
  { text: 'Fix major: link-urile facturilor/documentelor duceau la un deployment vechi dispărut (404) dacă erau urcate de pe alt domeniu decât apartpro.work — 23 de facturi reale reparate, link-urile noi sunt acum permanente indiferent de unde se face upload-ul', date: '2026-08-12' },
  { text: 'Fix facturi: eroare falsă „factura a mai fost încărcată" — verificarea de duplicat compara facturi din apartamente diferite (Urbica dă același nr. de referință la mai multe apartamente), plus AI-ul returna uneori "null" ca text — corectate 11 facturi reale afectate deja în arhivă', date: '2026-08-12' },
  { text: 'Statistici: selectezi apartamentul înainte de upload (nu mai depinde de auto-detectare AI) + click pe orice card deschide evoluția în timp a acelei proprietăți, cu toate metricile pe grafice', date: '2026-08-11' },
  { text: 'Stoc lenjerii: widget mai compact + apare acum și în Curățenie (admin), sincronizat cu Staff', date: '2026-08-11' },
  { text: 'Staff → Curățenie: stoc lenjerii disponibile sus în pagină — se adaugă manual, scade automat la fiecare curățenie terminată, alertă la stoc scăzut', date: '2026-08-11' },
  { text: 'Statistici: ghid pas-cu-pas pentru upload Airbnb, comparație cu anunțuri similare, timp pregătire rezervare + oaspeți care revin, fix salvare (poze multiple nu se mai suprascriau)', date: '2026-08-10' },
  { text: 'Fix major: rezervările cu check-out/plată în ultima zi a lunii (31, sau 30/28/29) lipseau din rapoarte, cheltuieli, deconturi, casă staff — bug de fus orar, reparat în 9 locuri din aplicație', date: '2026-08-07' },
  { text: 'Dashboard: fix clopoțel care bloca meniul mobil (☰) + eliminat proprietățile duplicate din listele de check-in/check-out de azi', date: '2026-08-07' },
  { text: 'Curățenie → Rapoarte: butoane „+ Sumă încasată" / „− Sumă cheltuită" înapoi în Casă staff, cu opțiune de ștergere pe fiecare intrare', date: '2026-08-06' },
  { text: 'Citit: istoricul din Statistici arată acum cartea, paginile și ora fiecărei sesiuni (când sunt mai multe într-o zi)', date: '2026-08-02' },
  { text: 'Mobil: fix apartamente (grid tăiat pe telefon), setări (panou inaccesibil), rezervări (filtre tăiate), cheltuieli (nume trunchiate), dashboard (antet aglomerat)', date: '2026-08-02' },
  { text: 'Citit: card redesenat — mai mic, mai discret, setările (ritm/durată) ascunse sub ⚙', date: '2026-08-02' },
  { text: 'Citit: buton „Am terminat", ștergere carte, coadă „De citit" pentru cărțile viitoare, estimare dată de finalizare pe baza ritmului tău', date: '2026-08-01' },
  { text: 'Citit: cartea curentă apare acum pe o linie cu săgeți ‹ › pentru navigare, iar paginile citite se pot edita direct (click pe numărul de pagini)', date: '2026-08-01' },
  { text: 'Citit: fix scanare copertă cu AI — folosea o cheie invalidă și dădea mereu eroare, acum funcționează', date: '2026-08-01' },
  { text: 'Task-uri: modul Citit extins — cărți multiple (fizic/digital), scanare copertă cu AI, tracking pagini pe bază de ritm, sesiune presetată, statistici per carte', date: '2026-08-01' },
  { text: 'Notificări: setări noi (⚙️ în clopoțel) pentru a alege categoriile primite — curățenie, eliberări, task-uri', date: '2026-08-01' },
  { text: 'Push: reparat bug de abonare (nu aștepta Service Worker-ul activ) + adăugat cheia lipsă din server', date: '2026-08-01' },
  { text: 'Notificări: clopoțel nou în aplicație + notificări push reparate (lipseau cheile VAPID)', date: '2026-08-01' },
  { text: 'Dashboard: banner automat pentru mesajele de confirmare check-in, la orice oră', date: '2026-07-31' },
  { text: 'Rapoarte: tab nou "Evoluție lunară" cu grafice ale totalurilor pe fiecare lună', date: '2026-07-31' },
  { text: 'Publi24: notița din fiecare cont se poate edita direct din casuță', date: '2026-07-31' },
  { text: 'Publi24: conturile se afișează acum pe 3 coloane (1 pe telefon)', date: '2026-07-30' },
  { text: 'Task-uri: fix accent roșu pe task-uri finalizate, spațiu între carduri, Publi24 restilizat ca în curățenie', date: '2026-07-30' },
  { text: 'Task-uri: culoare urgentă schimbată din roșu, drag-and-drop pentru reordonare, carduri mai compacte', date: '2026-07-30' },
  { text: 'Task-uri: kanban redesenat (culori, carduri) și responsive pe telefon', date: '2026-07-30' },
  { text: 'Publi24: conturi numerotate, email + parolă vizibile cu buton de copiat', date: '2026-07-30' },
  { text: 'Widget actualizări: mai mic, poziționat mai sus, numerotare Update N', date: '2026-07-30' },
  { text: 'Task-uri: adăugare rapidă pe coloane, rutină editabilă, tab Publi24', date: '2026-07-30' },
  { text: 'Staff: culori bani distincte de codul locker, navigare zi reparată', date: '2026-07-30' },
  { text: 'Bani de preluat: curățenie → staff → rapoarte, cu buton reset pe zi', date: '2026-07-29' },
  { text: 'Mesaj general pe zi, vizibil în curățenie și staff', date: '2026-07-29' },
  { text: 'Curățenie: card-uri reorganizate, telefon + WhatsApp la check-in/checkout', date: '2026-07-29' },
  { text: 'Domeniu propriu apartpro.work configurat', date: '2026-07-29' },
]
