export const UPDATES: { text: string; date: string }[] = [
  { text: 'Push: reparat bug de abonare (nu aștepta Service Worker-ul activ) + adăugat cheia lipsă din server', date: '2026-08-01' },
  { text: 'Notificări: clopoțel nou în aplicație + notificări push reparate (lipseau cheile VAPID)', date: '2026-08-01' },
  { text: 'Dashboard: banner automat pentru mesajele de confirmare check-in, la orice oră', date: '2026-07-31' },
  { text: 'Rapoarte: tab nou "Evoluție lunară" cu grafice ale totalurilor pe fiecare lună', date: '2026-07-31' },
  { text: 'Publi24: notița din fiecare cont se poate edita direct din casuță', date: '2026-07-31' },
  { text: 'Publi24: conturile se afișează acum pe 3 coloane (1 pe telefon)', date: '2026-07-30' },
  { text: 'Task-uri: fix accent roșu pe task-uri finalizate, spațiu între carduri, Publi24 restilizat ca în curățenie', date: '2026-07-30' },
  { text: 'Task-uri: culoare urgentă schimbată din roșu, drag-and-drop pentru reordonare, carduri mai compacte', date: '2026-07-30' },
  { text: 'Task-uri: kanban redesenat (culori, carduri) și responsive pe telefon', date: '2026-07-30' },
  { text: 'Publi24: conturi numerotate, email + parolă vizibile cu buton de copiat', date: '2026-07-30' },
  { text: 'Widget actualizări: mai mic, poziționat mai sus, numerotare Update N', date: '2026-07-30' },
  { text: 'Task-uri: adăugare rapidă pe coloane, rutină editabilă, tab Publi24', date: '2026-07-30' },
  { text: 'Staff: culori bani distincte de codul locker, navigare zi reparată', date: '2026-07-30' },
  { text: 'Bani de preluat: curățenie → staff → rapoarte, cu buton reset pe zi', date: '2026-07-29' },
  { text: 'Mesaj general pe zi, vizibil în curățenie și staff', date: '2026-07-29' },
  { text: 'Curățenie: card-uri reorganizate, telefon + WhatsApp la check-in/checkout', date: '2026-07-29' },
  { text: 'Domeniu propriu apartpro.work configurat', date: '2026-07-29' },
]
